# ////////////////////////////
# Config Logging Global Attributes
# ////////////////////////////
---
logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n %yellow(%logger{15}) -> %msg%n"
    rolling-file-name: logs/prod-sivaos-%d{yyyy-MM-dd}.%i.log
  file:
    name: "logs/prod-sivaos.log"

# ////////////////////////////
# Config Party 3rd Attributes
# ////////////////////////////
---
twilio:
  account-sid: ""
  account-auth-token: ""
  sender-number: ""
plivo:
  auth-id: ""
  auth-token: ""
  sender-number: ""

# ////////////////////////////
# Config 3rd Ally Attributes
# ////////////////////////////
---
spring:
  resource-server-callback-starter:
    host-auth: http://localhost:8083

# ////////////////////////////
# Config Spring Attributes
# ////////////////////////////
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/global_schema_oauth?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&characterSetResults=UTF-8
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    config:
      xml: hibernate-prod.cfg.xml
  redis:
    host: 127.0.0.1
    password: 123456***
    port: 6379
    sentinel:
      master:
        name: sivaos
      host-and-port: 13.232.155.79:26379;13.232.155.88:26379;13.232.154.78:26379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: quickstart-events
      partitions: 16
    consumer:
      topic: quickstart-events
      group-id: quickstart-events-id

