sivaos:
  app: ngx-blobs-uaa
  app-build: buildNgxBlobsUaa
  app-run: RUN_NGX_BLOBS_UAA
  app-jar: ngx-blobs-uaa
  swagger:
    description: API reference for developers
    contact-name: sivaos
    contact-url: https://github.com/pnguyen215
    contact-email: sivaglobalos@gmail.com
    license: sivaos 1.1
    license-url: https://swagger.io/license/
    version: v.1.1
  uaa:
    clientId: "sivaosUser"
    clientSecret: "sivaosU"
    clientHost: "localhost:8083"
