# PROD
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/global_schema?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&characterSetResults=UTF-8
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    config:
      xml: hibernate-prod.cfg.xml
  redis:
    host: 127.0.0.1
    password: sivaospassword
    port: 6379
    sentinel:
      master:
        name: sivaos
      host-and-port: 13.232.155.79:26379;13.232.155.88:26379;13.232.154.78:26379
# Hibernate Log levels
logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){faint}%n"
    rolling-file-name: logs/prod-sivaos-%d{yyyy-MM-dd}.%i.log
  file:
    name: "logs/prod-sivaos.log"
