# ////////////////////////////
# Config Logging Global Information
# ////////////////////////////
---
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web: DEBUG
  file:
    max-size: 2MB
    total-size-cap: 10MB
    max-history: 30
    clean-history-on-start: false
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"

# ////////////////////////////
# Config Spring Servlet Information
# ////////////////////////////
---
server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# ////////////////////////////
# Config Ngx SivaOs Org Information
# ////////////////////////////
---
sivaos:
  parts:
    upload-dir: roots

# ////////////////////////////
# Config Spring Information
# ////////////////////////////
---
spring:
  application:
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
  main:
    banner-mode: log
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: jwtSIVASecretKey
          jws-algorithm: RS256
  cache:
    couchbase:
      expiration: 846000
    cache-names: sivaos-cache-dev, sivaos-cache-local, sivaos-cache-prod
    redis:
      time-to-live: 60000
      cache-null-values: true
      time-expiry-hours: 23
      time-expiry-minutes: 59
      time-expiry-seconds: 59
  servlet:
    multipart:
      enabled: true
      max-file-size: 4GB
      max-request-size: 30MB
      file-size-threshold: 2KB
  mail:
    host: smtp.gmail.com
    port: 587

