# ////////////////////////////
# Config Params Attributes
# ////////////////////////////
---
sivaos:
  swagger:
    description: API reference for developers
    contact-name: sivaos
    contact-url: https://github.com/pnguyen215
    contact-email: sivaglobalos@gmail.com
    license: sivaos 1.1
    license-url: https://swagger.io/license/
    version: v.1.1
  authentication:
    client-id: "sivaosUser"
    client-secret: "sivaosU"
    host: "localhost:8083"
    protocol: "http://"
    enable: true
  cache:
    key-master: uaa
    callbacks:
      user-details:
        enabled: false

# ////////////////////////////
# Config Kafka Attributes
# ////////////////////////////
---
spring:
  kafka:
    enable-ssl: false
    sasl:
      enabled: false
    producer:
      enable-deep-config: false

# ////////////////////////////
# Config 3rd Ally Attributes
# ////////////////////////////
---
spring:
  resource-server-callback-starter:
    enabled: false # enable to check token from authorization server (url)

# ////////////////////////////
# Config Application Attributes
# ////////////////////////////
---
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh

# ////////////////////////////
# Config Cors Attributes
# ////////////////////////////
---
spring:
  cors-starter:
    enabled: true
    allow-credentials: true
    max-age-in-seconds: 1800
    allowed-origins:
      - '*' # default is any origins
    allowed-headers: # default ('*') is any headers
      - Authorization
      - Requestor-Type
    allowed-methods:
      - '*' # default is any methods (GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS, TRACE)
    exposed-headers: # not allowed for '*'
      - X-Get-Header
      - Access-Control-Expose-Headers
