spring:
  redis:
    database: 0 # Redis database index (default is 0)
    jedis:
      pool:
        max-active: 20 # Maximum connection number (no limit is limited)
        max-wait: -1 # Connect the pool maximum blocking waiting time (no limit is limited)
        max-idle: 10 # Connect the maximum idle connection in the pool
        min-idle: 0
    timeout: 10000 # Connect timeout (ms)
