# ////////////////////////////
# Config Geolocation Attributes
# ////////////////////////////
---
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
sivaos:
  geo:
    date-format: ${spring.jackson.date-format}
    time-zone: ${spring.jackson.time-zone}
    status: running
    name: vn

